# Google App Engine configuration for SafeBrowse
runtime: python39

# Environment variables
env_variables:
  DJANGO_SETTINGS_MODULE: safebrowse_project.settings
  SECRET_KEY: "django-insecure-!3%+y*=ypedb-8jt7+2^jf9ke)+*@518nh!1iua9$p$$0*0q*n"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DATABASE_URL: "sqlite:///db.sqlite3"
  
  # API Keys (replace with actual values)
  OPENAI_API_KEY: "your_openai_api_key_here"
  GOOGLE_SAFE_BROWSING_API_KEY: "your_safe_browsing_api_key_here"
  GOOGLE_CLIENT_ID: "your_google_client_id_here"
  GOOGLE_CLIENT_SECRET: "your_google_client_secret_here"
  
  # GCP Configuration
  GOOGLE_CLOUD_PROJECT: "your_project_id_here"
  GCP_STORAGE_BUCKET_NAME: "your_bucket_name_here"

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Static files handling
handlers:
- url: /static
  static_dir: staticfiles/
  secure: always

- url: /.*
  script: auto
  secure: always

# Skip files for deployment
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests$
- ^(.*/)?node_modules$
- ^(.*/)?venv$
- ^(.*/)?env$